cartographer_localize/TRAJECTORY_BUILDER.pure_localization_trimmer.max_submaps_to_keep: '15'
cartographer_localize/TRAJECTORY_BUILDER_2D.max_range: '16'
cartographer_localize/TRAJECTORY_BUILDER_2D.submaps.num_range_data: '60'
cartographer_mapping/TRAJECTORY_BUILDER_2D.max_range: '16'
cartographer_mapping/TRAJECTORY_BUILDER_2D.submaps.num_range_data: '60'
flexx2_back_filter/planeRansacDistThreshold: '0.07'
flexx2_left_filter/planeRansacDistThreshold: '0.07'
flexx2_right_filter/planeRansacDistThreshold: '0.07'
kinect_filter/planeRansacDistThreshold: '0.07'
